# Generated by Django 4.2.7 on 2026-01-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=10, unique=True)),
                ('hospital_name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('network_type', models.CharField(max_length=100)),
                ('coverage_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
    ]
