# Generated by Django 4.2.7 on 2026-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkprovider',
            options={'ordering': ['provider_id']},
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='coverage_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='hospital_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='network_type',
            field=models.CharField(choices=[('Cashless', 'Cashless'), ('Reimbursement', 'Reimbursement'), ('Cashless / Reimbursement', 'Cashless / Reimbursement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='provider_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
