# Generated by Django 4.2.7 on 2026-01-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_provider', '0002_alter_networkprovider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkprovider',
            name='coverage_limit',
            field=models.CharField(max_length=50),
        ),
    ]
