# Generated by Django 4.2.7 on 2026-01-06 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network_provider', '0003_alter_networkprovider_coverage_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkprovider',
            options={'ordering': ['provider_id'], 'verbose_name': 'Network Provider', 'verbose_name_plural': 'Network Providers'},
        ),
        migrations.AddField(
            model_name='networkprovider',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='networkprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='networkprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='coverage_limit',
            field=models.CharField(max_length=50, verbose_name='Coverage Limit'),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='hospital_name',
            field=models.CharField(max_length=200, verbose_name='Hospital Name'),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='location',
            field=models.CharField(max_length=300, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='network_type',
            field=models.CharField(choices=[('Cashless', 'Cashless'), ('Reimbursement', 'Reimbursement'), ('Cashless / Reimbursement', 'Cashless / Reimbursement')], max_length=50, verbose_name='Network Type'),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='provider_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Provider ID'),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Diagnostic Center', 'Diagnostic Center'), ('Pharmacy', 'Pharmacy'), ('Dental Clinic', 'Dental Clinic'), ('Eye Care', 'Eye Care')], max_length=100, verbose_name='Type'),
        ),
    ]
