# Generated by Django 4.2.7 on 2026-01-07 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network_provider', '0004_alter_networkprovider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkprovider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_providers', to=settings.AUTH_USER_MODEL),
        ),
    ]
