# Generated by Django 4.2.7 on 2026-01-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('policy_holder', 'Policy Holder'), ('network_provider', 'Network Provider')], max_length=20),
        ),
    ]
