# Generated by Django 4.2.7 on 2026-01-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_support', '0002_alter_category_options_alter_policy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
