# Generated by Django 4.2.7 on 2026-01-05 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_support', '0004_remove_feedback_comment_feedbackcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcomment',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to='feedback_support.feedback'),
        ),
    ]
