# Generated by Django 4.2.7 on 2025-12-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('filed_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(verbose_name='Reason for Claim')),
                ('document', models.FileField(blank=True, null=True, upload_to='claim_documents/')),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Admin Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_limit', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied/Pending Payment'), ('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], default='APPLIED', max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policy')),
            ],
            options={
                'verbose_name_plural': 'User Policies',
            },
        ),
    ]
