# Generated by Django 4.2.7 on 2025-12-12 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policy.userpolicy'),
        ),
        migrations.AlterUniqueTogether(
            name='userpolicy',
            unique_together={('user', 'policy')},
        ),
    ]
